---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Leo McKenna"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/final-project-1-leomckenna.git](https://github.com/stat301-1-2023-fall/final-project-1-leomckenna.git)

:::

## Data source

This data source is a compilation of Elo ratings and predictions from NFL games dating all the way back to 1920. This data was compiled by github user jayb for FiveThirtyEight. ^[https://github.com/fivethirtyeight/data/tree/master/nfl-elo]

## Why this data

I choose this data for a few reasons. Firstly, I'm a lifelong football fan, and I think the statistical side of the sport is largely unexplored. In the last few decades there has been an explosion of statistical study in sports like baseball, but football has been lagging behind, at least in the public sphere. I think there are so many fascinating things to be gleaned by looking at data like this. And it makes me feel good about being a Patriots fan.

Secondly, I am a competitive Scrabble player, and as a community we use the ELO rating system. However, I know almost nothing about it, and so I was hoping this data set could shed some light on how elo works and changes based on game outcomes.

## Data quality & complexity check

Blah blah blah

## Potential data issues

Because of poor documentation, there are many NA values especially in early games from the 20s through the 60s? - analyze. This could make it hard to look for trends over time, so it may be wise to analyze more recent data.

## Misc

Blah Blah
